version: '3.9'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq
      - ./init-scripts/rabbitmq:/init-scripts
    environment:
      RABBITMQ_DEFAULT_USER: metrobh
      RABBITMQ_DEFAULT_PASS: '!@UniqHub123'
    restart: always
    networks:
      metro-network:
        ipv4_address: 192.168.1.8
    # command: ["/bin/bash", "-c", "/init-scripts/setup.sh"]
    
  rabbitmqcore:
    container_name: rabbitmqCORE
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbit_data_core:/var/lib/rabbitmq
      - ./init-scripts/rabbitmq:/init-scripts
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: '!@Cittamobi123'
    restart: always
    networks:
      metro-network:
        ipv4_address: 192.168.1.19
    # command: ["/bin/bash", "-c", "/init-scripts/setup.sh"]

  mysqlcco:
    container_name: mysqlcco
    image: mysql:latest
    environment:
      #MYSQL_ROOT_PASSWORD: '!@UniqHub123'
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3309:3306"
    volumes:
      - mysqlcco_data:/var/lib/mysql
      - ./init-scripts/sqlcco:/docker-entrypoint-initdb.d
    restart: always
    networks:
      metro-network:
        ipv4_address: 192.168.1.15
        
  core:
    image: thalesuniq/brt-core-hml:latest
    container_name: core-cco
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlcco:3306/metroum?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: metrobh
      SPRING_RABBITMQ_PASSWORD: '!@UniqHub123'
      MONGO_HOST: 10.40.65.6
      MONGO_PORT: 27018
    ports:
      - "8103:8103"
    restart: always
    networks:
      metro-network:
        ipv4_address: 192.168.1.24

  interfaces-cco:
    image: thalesuniq/brt-interfaces-hml:latest
    container_name: interfaces-cco
    environment:
      SPRING_PROFILES_ACTIVE: hml
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlcco:3306/metroum?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: metrobh
      SPRING_RABBITMQ_PASSWORD: '!@UniqHub123'
      MONGO_HOST: 10.40.65.6
      MONGO_PORT: 27018
      BRT_CCO: "true"
    ports:
      - "8102:8102"
    restart: always
    networks:
      metro-network:
        ipv4_address: 192.168.1.16


  interfaces-sso:
    image: thalesuniq/brt-interfaces-hml:latest
    container_name: interfaces-sso
    environment:
      SPRING_PROFILES_ACTIVE: hml
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlcco:3306/metrodois?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: metrobh
      SPRING_RABBITMQ_PASSWORD: '!@UniqHub123'
      MONGO_HOST: 10.40.65.6
      MONGO_PORT: 27018
      BRT_CCO: "true"
    ports:
      - "8102:8102"
    restart: always
    networks:
      metro-network:
        ipv4_address: 192.168.1.23

  frontend-cco:
    image: thalesuniq/brt-operation-hml:latest
    container_name: frontend-cco
    environment:
          API_URL: http://hub_interfaces-cco:8102
    ports:
      - "4200:8200"
    restart: always
    networks:
      metro-network:
        ipv4_address: 192.168.1.17

  frontend-sso:
    image: thalesuniq/brt-operation-hml:latest
    container_name: frontend-sso
    environment:
          API_URL: http://hub_interfaces-sso:8101
    ports:
      - "4201:8201"
    restart: always
    networks:
      metro-network:
        ipv4_address: 192.168.1.22

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redis_data:/data
      - ./init-scripts/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    restart: always
    networks:
      metro-network:
        ipv4_address: 192.168.1.10

volumes:
  mysqlcco_data:
    external: true
  rabbit_data:
    external: true
  redis_data:
    external: true

networks:
  metro-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
